# Numpy <hr style="border:2.5px solid #1b92c5ff"></hr>

<b>Vince Saimon Canencia</b>
<br>CpE2A</b>


In [2]:
#imports and packages
import numpy as np

# 1D Array

In [7]:
my_array = [1,2,3]

In [8]:
type(my_array)

list

In [5]:
my_array = np.array([1,2,3])

In [9]:
np.shape(my_array)

(3,)

# 2D Array

In [14]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.shape(my_array)

(2, 3)

In [16]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
trans_array = my_array.T

In [19]:
trans_array


array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency

In [28]:
resistance = np.array({
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8], #Jaguar
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan] #Panther
})

TypeError: cannot use 'list' as a set element (unhashable type: 'list')