# Numpy <hr style="border:2.5px solid #1b92c5ff"></hr>

<b>Vince Saimon Canencia</b>
<br>CpE2A</b>


In [34]:
#imports and packages
import numpy as np

# 1D Array

In [35]:
my_array = [1,2,3]

In [36]:
type(my_array)

list

In [37]:
my_array = np.array([1,2,3])

In [38]:
np.shape(my_array)

(3,)

# 2D Array

In [39]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.shape(my_array)

(2, 3)

In [41]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [42]:
trans_array = my_array.T

In [43]:
trans_array


array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency

In [45]:
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8], #Jaguar
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan] #Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [ ]:
#Mean
np.mean(resistance,axis=1)


array([9.4, nan])