# Numpy <hr style="border:2.5px solid #1b92c5ff"></hr>

<b>Vince Saimon Canencia</b>
<br>CpE2A</b>


In [66]:
# %pip install numpy --upgrade
# %pip install scipy --upgrade

In [67]:
# %pip install --upgrade pip

In [68]:
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [69]:
array_a = np.array([1, 2, 3])
array_a

array([1, 2, 3])

In [70]:
np.shape(array_a)

(3,)

In [71]:
array_b = np.array([[4, 5, 6]])
array_b

array([[4, 5, 6]])

In [72]:
np.shape(array_b)

(1, 3)

# 2D Array

In [73]:
my_array = np.array([[1, 2, 3],
                     [4, 5, 6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np.shape(my_array)

(2, 3)

In [75]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
np.shape(t_array)

(3, 2)

# Measure of Central Tendency

In [77]:
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8], #Jaguar
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan] #Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [78]:
np.shape(resistance)

(2, 11)

In [79]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

In [80]:
np.mean(resistance, axis=0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.05,   nan])

In [81]:
 np.mean(resistance, axis=1)

array([9.4, nan])

In [82]:
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])

In [83]:
jag_mean = np.nanmean(resistance, axis=1)[0]
pan_mean = np.nanmean(resistance, axis=1)[1]
print(f'\nJaguar_mean = {jag_mean:.2f} ohms')
print(f'Panther_mean = {pan_mean:.2f} ohms')



Jaguar_mean = 9.40 ohms
Panther_mean = 10.75 ohms


In [84]:
nanmedian_result = np.nanmedian(resistance, axis=1)

In [85]:
jag_median = np.nanmedian(resistance, axis=1)[0]
pan_median = np.nanmedian(resistance, axis=1)[1]
print(f'\nJaguar_median = {jag_median:.2f} ohms')
print(f'Panther_median = {pan_median:.2f} ohms')


Jaguar_median = 9.80 ohms
Panther_median = 9.55 ohms


In [86]:
stats.mode(resistance, axis=1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [87]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [88]:

jag_res = resistance[0]

print("Jaguar mode:")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar mode:
9.8 ohms
10.4 ohms


In [89]:
pan_res = resistance[1]

print("Panther mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther mode:
9.1 ohms


# Measures of Variablitiy

In [90]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [91]:
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [92]:
print(f'Jaguar_range = {res_range[0]:.2f} ohms')
print(f'Panther_range = {res_range[1]:.2f} ohms')

Jaguar_range = 8.00 ohms
Panther_range = 10.90 ohms


In [93]:
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.4  , 9.125])

In [94]:
res_Q2 = np.nanpercentile(resistance, 50, axis=1)
res_Q2

array([9.8 , 9.55])

In [95]:
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3

array([10.45 , 10.625])

In [96]:
print(f'Jaguar IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR = 1.05 ohms
Panther IQR = 1.50 ohms


In [97]:
res_var = np.nanvar(resistance, ddof=1, axis=1)
res_var

array([ 4.86      , 11.08277778])

In [98]:
print(f'Jaguar Variance = {res_var[0]:.2f} ohms')
print(f'Panther Variance = {res_var[1]:.2f} ohms')

Jaguar Variance = 4.86 ohms
Panther Variance = 11.08 ohms


In [99]:
res_std = np.nanstd(resistance,ddof=1,axis=1)
res_std

array([2.20454077, 3.32908062])

In [100]:
print(f'Jaguar Standard Deviation = {res_std[0]:.2f} ohms')
print(f'Panther Standard Deviation = {res_std[1]:.2f} ohms')

Jaguar Standard Deviation = 2.20 ohms
Panther Standard Deviation = 3.33 ohms
